define

naptan-id sub attribute datatype string;
name sub attribute datatype string;
lat sub attribute datatype double;
lon sub attribute datatype double;
direction sub attribute datatype string;
identifier sub attribute datatype long;
duration sub attribute datatype long;

zone sub entity,
    plays within,
    has name;

zoning sub relationship,
    relates within,
    relates contains-stop;

stop sub entity,
    plays goes-from,
    plays goes-to,
    plays contains-stop,
    plays originates-at,
    plays terminates-at,
    has naptan-id
    has name,
    has lat,
    has lon;

line sub entity,
    has name,
    has identifier;

route sub entity,
    plays operates,
    plays part-of,
    has identifier;

route-section sub relationship,
    relates part-of,
    relates goes-from,
    relates goes-to,
    has duration;

origin-route-section sub route-section,
    relates originates-at as goes-from,
    relates part-of,
    relates goes-to;

termination-route-section sub route-section,
    relates terminates-at,
    relates part-of,
    relates goes-from;

service sub entity,
    plays operated-by,
    has name;

operation sub relationship,
    relates operated-by,
    relates operates;
