define

naptan-id sub attribute datatype string;
name sub attribute datatype string;
lat sub attribute datatype double;
lon sub attribute datatype double;
direction sub attribute datatype string;
identifier sub attribute datatype long;
duration sub attribute datatype long;
is-origin sub attribute datatype boolean;
is-termination sub attribute datatype boolean;

zone sub entity,
    plays within,
    has name;

zoning sub relationship,
    relates within,
    relates contains-stop;

stop sub entity,
    plays goes-from,
    plays goes-to,
    plays originates-at,
    plays terminates-at,
    plays contains-stop,
    has naptan-id
    has name,
    has lat,
    has lon;

line sub entity,
    has name,
    has identifier;

route sub entity,
    plays operates,
    plays part-of,
    plays has-route,
    has identifier;

route-section sub relationship,
    relates part-of,
    relates goes-from,
    relates goes-to,
    has duration,
    has is-origin,
    has is-termination;

service sub entity,
    plays operated-by,
    has name;

operation sub relationship,
    relates operated-by,
    relates operates;

origination sub relationship,
    relates originates-at,
    relates has-route;

termination sub relationship,
    relates terminates-at,
    relates has-route;

find-origin sub rule,
    when {
        $s isa stop;
        $r isa route;
        $rs(goes-from: $s, part-of: $r) isa route-section, has is-origin val true;
    } then {
        (originates-at: $s, has-route: $r) isa origination;
    };

find-termination sub rule,
    when {
        $s isa stop;
        $r isa route;
        $rs(goes-to: $s, part-of: $r) isa route-section, has is-termination val true;
    } then {
        (terminates-at: $s, has-route: $r) isa termination;
    };
