
# a <relationship> has a <role> in the form of a <subject> (<subject> is a concept, which could be an entity, relationship, or attribute)

define

naptan-id sub attribute datatype string;
name sub attribute datatype string;
lat sub attribute datatype double;
lon sub attribute datatype double;
duration sub attribute datatype long;
distance sub attribute datatype double;


station sub entity,
	plays stop,
	plays start,
	plays end,
    plays origin,
    plays destination,
	plays contained-station,
	plays neighbour,
	has naptan-id,
    has name,
    has lat,
    has lon;


route sub relationship,
	# a <route> has a <section> in the form of a <route-section>
	relates section, # is <section> too vague?
	# a <route> has a <stop> in the form of a <station>	
	relates stop,

	# a <route> has a <origin> as a <stop> in the form of a <station>
	relates origin as stop,

	# a <route> has a <destination> as a <stop> in the form of a <station>
	relates destination as stop,

	# a <route> has a <service/operator/agent/handler/service-provider/provider/facilitator/enabler/route-line> in the form of a <line>
	# why route-line or route-operator and not something else? Because the other terms are vague, and could describe a 
	# lot of other roles, whereas route-line substitutes for where we cannot find a name, but can generate something specific
	
	# a West Ruislip to Epping route has a <route-line/route-operator> in the form of the Central Line
	relates route-operator;


route-section sub entity,

	# a <route-section> plays the role of <section> in a <route>
	# a <route-section> relates to a <route> as a <section>
	# You could replace this entity with the timetabled duration, but that wouldn't be open to extensibility if we later wanted to add more information about that route section
	plays section,
	plays service,
	has duration;


tunnel sub relationship, # could be called a link, transport-link, track-section or tunnel
	# a <tunnel> has a <start> in the form of a <station>
	relates start,

	# a <tunnel> has a <end> in the form of a <station>
	relates end,

	# a <tunnel> has a <linking-section> in the form of a <route-section>
	# a <tunnel> has a <fulfillment/actuation/tube-link/link/connection/service> in the form of a <route-section>
	# a <tunnel> has a <service> in the form of a <route-section>
	relates service;

	#has distance;  # If link is directional than this would exist twice if included here. Would be better as a seperate <neighbourship> relationship


tube-line sub entity,
	plays route-operator,
	has name;


zone sub relationship,
	# a <zone> has a <contained-station> in the form of a <station>
	relates contained-station,
	# usage: $z(contained-station: $station1, contained-station: $station2) isa zone;
	has name;


neighbourship sub relationship,
	# a <neighbourship> has a <neighbour> in the form of a <station>
	relates neighbour,
	has distance;
